"""empty message

Revision ID: 19d89b66c622
Revises: b703740ec992
Create Date: 2026-02-24 11:25:16.372344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d89b66c622'
down_revision: Union[str, Sequence[str], None] = 'b703740ec992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coins_short_name'), table_name='coins')
    op.create_index(op.f('ix_coins_name'), 'coins', ['name'], unique=True)
    op.drop_column('coins', 'short_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_coins_name'), table_name='coins')
    op.create_index(op.f('ix_coins_short_name'), 'coins', ['short_name'], unique=True)
    # ### end Alembic commands ###
