"""empty message

Revision ID: 373c851c967e
Revises: a190612355f3
Create Date: 2026-02-13 17:28:24.941113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '373c851c967e'
down_revision: Union[str, Sequence[str], None] = 'a190612355f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_hashed_password_',
               existing_type=postgresql.BYTEA(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_hashed_password_',
               existing_type=postgresql.BYTEA(),
               server_default=sa.text("'\\x70617373776f7264'::bytea"),
               existing_nullable=False)
    # ### end Alembic commands ###
