"""empty message

Revision ID: 499961bcdcbe
Revises: 1c72dd7e50fb
Create Date: 2026-02-18 12:41:37.817632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499961bcdcbe'
down_revision: Union[str, Sequence[str], None] = '1c72dd7e50fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expire', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('otp_try', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_try')
    op.drop_column('users', 'otp_expire')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
