"""empty message

Revision ID: f7dbdbac4546
Revises: 373c851c967e
Create Date: 2026-02-16 17:11:01.248750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7dbdbac4546'
down_revision: Union[str, Sequence[str], None] = '373c851c967e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('jti', sa.String(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('refresh_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'user_id')
    op.drop_column('refresh_tokens', 'expire_at')
    op.drop_column('refresh_tokens', 'jti')
    # ### end Alembic commands ###
